spring:
  ## Application Name
  application:
    name: EXPENSES-REST
  ## Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/ENGAGETECHDB
    username: root
    password: toortoor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

## Vat Config
vat:
  percentage: 20

## Jwt Config
jwt:
  secret: sDSFjhhJH@__3546466-*/_--@@@888bsdfsdfsdf

## Currency API Uri
com:
  engage:
    currency:
      uri: https://api.exchangeratesapi.io
    allowed-origins: localhost:4200,localhost:3000